### ISSUE TITLE
key_registration_header.svg is hard to read when the reader's browser is dark mode.

### ISSUE THREAD

**Issue by aawc** [WICG/dbsc#15]
Steps to reproduce:
1. Set browser to dark mode.
2. Open https://github.com/WICG/dbsc/blob/main/README.md#start-session
3. Observe that https://github.com/WICG/dbsc/blob/main/key_registration_header.svg is rendered in a way that makes it hard to read (likely because the `.svg` has a transparent background?)

![Screenshot 2024-01-12 at 15 59 19](https://github.com/WICG/dbsc/assets/423205/89f33503-e558-454b-adf6-fa979a09f25c)

Chrome version (not sure it matters): `121.0.6167.57`

Note that https://github.com/WICG/dbsc/blob/main/reg_and_refresh.svg renders correctly

**Comment by aawc** [comment]
Same problem with https://github.com/WICG/dbsc/blob/main/refresh_diagram.svg and https://github.com/WICG/dbsc/blob/main/key_registration.svg

**Comment by kmonsen** [comment]
Fixed with:
https://github.com/WICG/dbsc/commit/d5a88afa3e167769555e4dc268874feb997b2146
https://github.com/WICG/dbsc/commit/36c4c32e352d4211d3c13e44e95602423f23caad
https://github.com/WICG/dbsc/commit/1faa6b9e48584ac5e45b2b4524edefbe306c6449
https://github.com/WICG/dbsc/commit/b4c24a1046a2d98e0b11544218c3dd6d7dd61e80
https://github.com/WICG/dbsc/commit/d6007a68995844a174fb22573085f765e6144a5c
https://github.com/WICG/dbsc/commit/dafaa9c9f92b57ecb8bfb0e353a16ebf4130429f
